### ISSUE TITLE
Nothing happens after clicking 'Run' on popup after double clicking exe

### ISSUE THREAD

**Issue by jameswilliamknight** [bertjohnson/ExtractIcon#1]
OS Name	Microsoft Windows 10 Pro
Version	10.0.18362 Build 18362
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Manufacturer	System manufacturer
System Model	System Product Name
System Type	x64-based PC
System SKU	SKU
Processor	Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz, 4200 Mhz, 4 Core(s), 8 Logical Processor(s)

**Comment by liuyike98** [comment]
this is a command line application.... do not double click directly,but use cmd.exe to execute it.

**Comment by jameswilliamknight** [comment]
thank you. we can probably close this.
